# Generated by Django 4.0.1 on 2022-02-03 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticker',
            name='mail_sent',
            field=models.BooleanField(default=False),
        ),
    ]
