# Generated by Django 4.0.1 on 2022-02-03 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_ticker_mail_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticker',
            name='dividend_type',
            field=models.CharField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticker',
            name='ex_dividend_date',
            field=models.CharField(default='test', max_length=254),
            preserve_default=False,
        ),
    ]
