# Generated by Django 3.2.4 on 2022-09-25 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20220925_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='nse_bse_dividend_alerts',
            name='face_value',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
